char *_strcat(char *dest, char *src);
char *infinite_add(char *n1, char *n2, char *r, int size_r);
char _putchar(char c);
void print_number(int n);
char *leet(char *);
int max(int a, int b);
int _strcmp(char *s1, char *s2);
char *cap_string(char *);
char *string_toupper(char *);
void reverse_array(int *a, int n);
char *_strncat(char *dest, char *src, int n);
char *_strncpy(char *dest, char *src, int n);
